/* Generated By:JavaCC: Do not edit this line. ColorParserConstants.java */
package sandbox.colors.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ColorParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int SIGN = 6;
  /** RegularExpression Id. */
  int EXPONENT = 7;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 8;
  /** RegularExpression Id. */
  int INT_NUMBER = 9;
  /** RegularExpression Id. */
  int HEXACHAR = 10;
  /** RegularExpression Id. */
  int HEXA = 11;
  /** RegularExpression Id. */
  int RGBA = 12;
  /** RegularExpression Id. */
  int RGB = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int NAMED = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "<SIGN>",
    "<EXPONENT>",
    "<FLOATING_NUMBER>",
    "<INT_NUMBER>",
    "<HEXACHAR>",
    "<HEXA>",
    "\"rgba\"",
    "\"rgb\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<LETTER>",
    "<NAMED>",
  };

}
