/* Generated By:JavaCC: Do not edit this line. StreamPlotParserConstants.java */
package sandbox.tools.streamplot.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StreamPlotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OFUN = 9;
  /** RegularExpression Id. */
  int OPAR = 10;
  /** RegularExpression Id. */
  int CPAR = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int QUESTION = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int EQ = 17;
  /** RegularExpression Id. */
  int NE = 18;
  /** RegularExpression Id. */
  int LE = 19;
  /** RegularExpression Id. */
  int GE = 20;
  /** RegularExpression Id. */
  int LT = 21;
  /** RegularExpression Id. */
  int GT = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int MUL = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int LINE = 27;
  /** RegularExpression Id. */
  int ASSIGN = 28;
  /** RegularExpression Id. */
  int LEX_TRUE = 29;
  /** RegularExpression Id. */
  int LEX_FALSE = 30;
  /** RegularExpression Id. */
  int LEX_NIL = 31;
  /** RegularExpression Id. */
  int WIDTH = 32;
  /** RegularExpression Id. */
  int HEIGHT = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;
  /** RegularExpression Id. */
  int SIGN = 36;
  /** RegularExpression Id. */
  int EXPONENT = 37;
  /** RegularExpression Id. */
  int PERCENT = 38;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 39;
  /** RegularExpression Id. */
  int INT_NUMBER = 40;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 42;
  /** RegularExpression Id. */
  int SIMPLE_QUOTE_LITERAL = 43;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_LITERAL = 44;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<OFUN>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\"?\"",
    "\".\"",
    "\",\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"line\"",
    "\"=\"",
    "\"true\"",
    "\"false\"",
    "\"nil\"",
    "\"width\"",
    "\"height\"",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
    "<EXPONENT>",
    "<PERCENT>",
    "<FLOATING_NUMBER>",
    "<INT_NUMBER>",
    "<IDENTIFIER>",
    "<ESCAPE_CHAR>",
    "<SIMPLE_QUOTE_LITERAL>",
    "<DOUBLE_QUOTE_LITERAL>",
  };

}
