/* Generated By:JavaCC: Do not edit this line. StreamPlotParserConstants.java */
package sandbox.tools.streamplot.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StreamPlotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int O_BRACKET = 5;
  /** RegularExpression Id. */
  int C_BRACKET = 6;
  /** RegularExpression Id. */
  int O_PAR = 7;
  /** RegularExpression Id. */
  int C_PAR = 8;
  /** RegularExpression Id. */
  int ASSIGN = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int TYPE_INT_RGB = 11;
  /** RegularExpression Id. */
  int IMAGE = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int SIGN = 15;
  /** RegularExpression Id. */
  int DOT1 = 16;
  /** RegularExpression Id. */
  int EXPONENT = 17;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 18;
  /** RegularExpression Id. */
  int INT_NUMBER = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "\"TYPE_INT_RGB\"",
    "\"image\"",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
    "\".\"",
    "<EXPONENT>",
    "<FLOATING_NUMBER>",
    "<INT_NUMBER>",
    "<DOT>",
    "<IDENTIFIER>",
  };

}
