/* Generated By:JavaCC: Do not edit this line. LispParserConstants.java */
package sandbox.lisp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LispParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPAR = 6;
  /** RegularExpression Id. */
  int CPAR = 7;
  /** RegularExpression Id. */
  int OARRAY = 8;
  /** RegularExpression Id. */
  int CARRAY = 9;
  /** RegularExpression Id. */
  int LEX_TRUE = 10;
  /** RegularExpression Id. */
  int LEX_FALSE = 11;
  /** RegularExpression Id. */
  int LEX_NIL = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int SIGN = 15;
  /** RegularExpression Id. */
  int DOT = 16;
  /** RegularExpression Id. */
  int QUOTE = 17;
  /** RegularExpression Id. */
  int EXPONENT = 18;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 19;
  /** RegularExpression Id. */
  int INT_NUMBER = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 22;
  /** RegularExpression Id. */
  int SIMPLE_QUOTE_LITERAL = 23;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_LITERAL = 24;
  /** RegularExpression Id. */
  int OTHER = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"#t\"",
    "\"#f\"",
    "\"null\"",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
    "\".\"",
    "\"\\\'\"",
    "<EXPONENT>",
    "<FLOATING_NUMBER>",
    "<INT_NUMBER>",
    "<IDENTIFIER>",
    "<ESCAPE_CHAR>",
    "<SIMPLE_QUOTE_LITERAL>",
    "<DOUBLE_QUOTE_LITERAL>",
    "<OTHER>",
  };

}
