/* LispParser.java */
/* Generated By:JavaCC: Do not edit this line. LispParser.java */
package sandbox.lisp;
import java.util.List;
import java.util.ArrayList;
import java.math.BigDecimal;
import java.math.BigInteger;
import sandbox.lang.StringUtils;


@SuppressWarnings("unchecked")
public class LispParser implements LispParserConstants {

  final public LispNode any() throws ParseException {LispNode n=null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPAR:{
      n = listNode();
      break;
      }
    case OARRAY:{
      n = arrayNode();
      break;
      }
    case LEX_TRUE:
    case LEX_FALSE:
    case LEX_NIL:
    case FLOATING_NUMBER:
    case INT_NUMBER:
    case SIMPLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
    case OTHER:{
      n = atomNode();
      break;
      }
    case 0:{
      jj_consume_token(0);
{if ("" != null) return null;}
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  final private LispList listNode() throws ParseException {LispList L=new LispList();LispNode n=null;
    jj_consume_token(OPAR);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 0:
      case OPAR:
      case OARRAY:
      case LEX_TRUE:
      case LEX_FALSE:
      case LEX_NIL:
      case FLOATING_NUMBER:
      case INT_NUMBER:
      case SIMPLE_QUOTE_LITERAL:
      case DOUBLE_QUOTE_LITERAL:
      case OTHER:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      n = any();
L.add(n);
    }
    jj_consume_token(CPAR);
{if ("" != null) return L;}
    throw new Error("Missing return statement in function");
}

  final private LispArray arrayNode() throws ParseException {List<Object> L=new ArrayList<Object>();LispAtom<?> n=null;
    jj_consume_token(OARRAY);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LEX_TRUE:
      case LEX_FALSE:
      case LEX_NIL:
      case FLOATING_NUMBER:
      case INT_NUMBER:
      case SIMPLE_QUOTE_LITERAL:
      case DOUBLE_QUOTE_LITERAL:
      case OTHER:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      n = atomNode();
L.add(n.getValue());
    }
    jj_consume_token(CARRAY);
{if ("" != null) return LispArray.from(L);}
    throw new Error("Missing return statement in function");
}

  final private LispAtom<?> atomNode() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEX_TRUE:{
      jj_consume_token(LEX_TRUE);
{if ("" != null) return LispJavaObject.TRUE;}
      break;
      }
    case LEX_FALSE:{
      jj_consume_token(LEX_FALSE);
{if ("" != null) return LispJavaObject.FALSE;}
      break;
      }
    case LEX_NIL:{
      jj_consume_token(LEX_NIL);
{if ("" != null) return LispJavaObject.NIL;}
      break;
      }
    case INT_NUMBER:{
      t = jj_consume_token(INT_NUMBER);
final BigInteger bi = new BigInteger(t.image);
                {if ("" != null) return LispJavaObject.of(bi);}
      break;
      }
    case FLOATING_NUMBER:{
      t = jj_consume_token(FLOATING_NUMBER);
final BigDecimal bd = new BigDecimal(t.image);
                {if ("" != null) return LispJavaObject.of(bd);}
      break;
      }
    case SIMPLE_QUOTE_LITERAL:{
      t = jj_consume_token(SIMPLE_QUOTE_LITERAL);
{if ("" != null) return LispJavaObject.of(StringUtils.unquote(t.image));}
      break;
      }
    case DOUBLE_QUOTE_LITERAL:{
      t = jj_consume_token(DOUBLE_QUOTE_LITERAL);
{if ("" != null) return LispJavaObject.of(StringUtils.unquote(t.image));}
      break;
      }
    case OTHER:{
      t = jj_consume_token(OTHER);
{if ("" != null) return LispSymbol.of(t.image);}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  /** Generated Token Manager. */
  public LispParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[4];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xe61d41,0xe61d41,0xe61c00,0xe61c00,};
	}

  /** Constructor with InputStream. */
  public LispParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public LispParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new LispParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public LispParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new LispParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new LispParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public LispParser(LispParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(LispParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[24];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 4; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 24; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
