/* Generated By:JavaCC: Do not edit this line. SVGTransformParserConstants.java */
package sandbox.svg.transform;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SVGTransformParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPAR = 1;
  /** RegularExpression Id. */
  int CPAR = 2;
  /** RegularExpression Id. */
  int DOT = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int POSITIVE_INTEGER = 8;
  /** RegularExpression Id. */
  int SIGN = 9;
  /** RegularExpression Id. */
  int EXPONENT = 10;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 11;
  /** RegularExpression Id. */
  int TRANSLATE = 12;
  /** RegularExpression Id. */
  int ROTATE = 13;
  /** RegularExpression Id. */
  int SCALE = 14;
  /** RegularExpression Id. */
  int SKEWX = 15;
  /** RegularExpression Id. */
  int SKEWY = 16;
  /** RegularExpression Id. */
  int MATRIX = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "<DIGIT>",
    "<POSITIVE_INTEGER>",
    "<SIGN>",
    "<EXPONENT>",
    "<FLOATING_NUMBER>",
    "\"translate\"",
    "\"rotate\"",
    "\"scale\"",
    "\"skewX\"",
    "\"skewY\"",
    "\"matrix\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
